#
###################################
# Site wide configuration
####################################
#
title: Gthree
email: hznaug6211@163.com
description: G_three's blog,powered by jekyll
url: https://hejiayangzh.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Java", "Android","Blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          xingyang/henan
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: G_three
  avatar: mylogo.png
  job: "JakartaEE & Android Developer"
  bio: "一位向虎山的JakartaEE, Android 开发者"
  email: hznaug6211@163.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hejiayangzh #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
